### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Najeeba-Qarqin**
This is repository is just for test and learn the GitHub workflows and git commands.

### CODE REVIEW

**Comment by Najeeba-Qarqin** [comment]
@ahzamir
I added meaningful PR descriptions to this PR.
And I don't have the node modules in my repository and folder but there is error from node modules.

**Comment by ahzamir** [comment]
@Najeeba-Qarqin 

I think you changed something in the linters files config so it is giving you this error:
- In order to solve this You can delete `.github` folder and all the linters files (`.hintrc`, `.stylelintrc`)and add them back from the drive.

**Comment by Najeeba-Qarqin** [comment]
It's done @ahzamir thank you!

**Comment by ahzamir** [comment]
### Hi @Najeeba-Qarqin 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Odin Project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
